learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'

urlpatterns=[

    url(r'^online/$',views.online,name='online'),
    url(r'^code/$',views.code,name='code'),
    url(r'^downloads/$',views.downloads,name='downloads'),
    # url(r'^index/$',views.index,name='index'),
    # url(r'^ML/$',views.ML,name='ML'),
    url(r'^photos/$',views.photos,name='photos'),]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url,include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^$',views.index,name ='index'),
]

learning_templates/templates/basic_app/learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/templates/basic_app/learning_templates/learning_templates/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/templates/basic_app/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

def index(request):
    return render(request,'basic_app/index.html')
def photos(request):
    return render(request,'basic_app/photos.html')
def code(request):
    return render(request,'basic_app/code.html')
def downloads(request):
    return render(request,'basic_app/downloads.html')
def online(request):
    return render(request,'basic_app/online.html')

learning_templates/templates/basic_app/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>

          <li><a class="navbar-link" href="{% url 'basic_app:online' %}">Online</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:downloads' %}">Downloads</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:code' %}">Code</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:photos' %}">Photos</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <!-- <li><a class="navbar-link" href="{% url 'basic_app:online' %}">Online</a></li> -->
        </ul>
      </div>
    </nav>
    <div class="container">



    {% block body_block %}
    <!-- {# Anything outside of this will be inherited if you use extend.#} -->
    {% endblock %}
    </div>


  </body>
  <!-- <canvas id="canvas"></canvas> -->

  <!-- <script type="text/javascript" src="{% static 'simplesocial/js/master.js'%}"> -->
  </script>
  <!-- </span> -->
</html>

learning_templates/templates/basic_app/code.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% load static %}
  {% block body_block %}
  <link rel="stylesheet" href="{% static "css/mystyle.css"%}"/>
  <h1><u>Code of Raspberry Pi</u></h1>
  <pre id="description">
  import sys
        import Rpi.GPIO as GPIO
        import os
        import Adafruit_DHT
        import urllib2
        import smbus
        import time
        from ctypes import c_short
        DHTpin = 17
        key="XKYP3AJOMVVTL7C1"
        GPIO.setmode(GPIO.BCM)
        def readDHT():
            humi, temp = Adafruit_DHT.read_retry(Adafruit_DHT.DHT11, DHTpin)
            return (str(int(humi)), str(int(temp)))

        # main() function
        def main():

            print 'System Ready...'
            URL = 'https://api.thingspeak.com/update?api_key=XKYP3AJOMVVTL7C1&field1=0'
            print "Wait...."
            while True:
                (hum1, temp)= readDHT()

                finalURL = URL +"&field1=%s&field2=%s"%(humi, temp)
                print finalURL
                s=urllib2.urlopen(finalURL);
                print humi+ " " + temp + " "
                s.close()
                time.sleep(10)


  </pre>

  {% endblock %}

learning_templates/templates/basic_app/downloads.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}

    <h1>welcome to other</h1>
    <h2>this an example of inheritance</h2>

  {% endblock %}

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html"%}
{% load static %}
  {% block body_block %}
  <link rel="stylesheet" href="{% static "css/mystyle.css"%}"/>
    <h1>Welcome</h1>
    <h2>Description about the project</h2>
    <h4>Agriculture is an expensive and widly wasteful industry.It requores a lot of manpower and management. On top of this requires a lot of man power and management.On top of this the crops require special care and nurturing conditions for a fruitful harvest. Nowadays the number of people who want to work in farms had become very less. This has caused a crisis in rural areas and farmers are not able to grow the adequate amount of crop or grow crops which require a lot of manpower. We have devised a solution for this problem which can not deal with problems stated above but also do it more efficiently.</h4>
    <h2>About the Bot</h2>
    <h4>The bot contains a chassis which has an attached plougher and also an attached gantry which has a tool mount arm. The tool mount arm can perform tasks like supplying water,fertilizer and sowing seeds. The tool mount arm also has an attached claw to harvest certain kind of crops and an ultrasonic sensor at the tip to help it to navigate on the field. Soil moisture is traked using the moisture sensor on the arm and the field is irrigated on the basis of that.</h4>
    <h2>Features</h2>
    <p><ul>
			<h3><li>Ploughing</li></h3>
			<h4><p>Ploughing is one of the most essential task in farming. Keeping this in mind we have added the feature of attachable and de-attachable plougher. The flougher can be fixed at the very starting of the bot and it would plough the field. This has an arrangement of sharp plougher which could be slided into the bot's front. As the bot set to the ploughing mode it would traverse through the field in X axis ploughing it.</p></h4>
			<h3><li>Seed Sowing</li></h3>
			<h4><p> As the bot has feature of 3 Dimensional traversal it very easy for the bot to perform the task such as seed sowing or irrigation or fertilizer spraying. The Z axis arm performs these tasks of seed sowing as it has cantainer which is equipped with the feature of dropping down the seed at the precisie position. The feature of precision adds a lot of value to our project as this allows us to save resources(water,seed,fertilizer). The arm has a container which is filled with the seeds. This container when turned it would allow the seeds to drop down. The process of opening the container is performed by the servo motor which is controlled by raspberrypi.</p></h4>
			<h3><li>Irrigation</li></h3>
			<h4><p>Now as the field had been ploughed and seed sowing done. We need to water these seeds. The feature of irrigating the field is done by the arm in the bot. The bot is equipped with a water tank which has a water-pump through which water is sprayed to the seeds with precision of amount of water and position.</p></h4>
			<h3><li>Fertilizer Spraying</li></h3>
			<h4><p>Since the plants need proper nutrition for there growth the arm also ejects the fertilizer using the same mechanism of water spraying.</p></h4>
			<h3><li>Moisture Tracking</li></h3>
			<h4><p>Since water is a crucial the moisture tracking helps us to save it. The soil moisture sensor sends the data to the device about amount of water it has or is required. And as per that water is sprayed or turned off.</p></h4>
			<h3><li>Data prediction</li></h3>

		</ul></p>
    <h2>Flowchart</h2>
    <p style="text-align:center;"><img src="{% static "images/flowchart.jpg" %}" alt="Error, no pic"></p>


  {% endblock %}

learning_templates/templates/basic_app/learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">



    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>


  </body>
</html>

learning_templates/templates/basic_app/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is index.html page showing!</h2>
  {% endblock %}

learning_templates/templates/basic_app/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>THis is an example of template inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Urls</title>
  </head>
  <body>
    <h1>Welcome!</h1>
    <p>
      This page serves as an example of how to
      use relative urls with templates!
      This is the relative_url_templates.html file.
    </p>

    {# Here are the examples:#}
    {# Must set the app_name=basic_app variable inside the basic_app/urls.py#}
    <a href="{% url 'admin:index' %}">Link to Admin Page</a>

    <a href="{% url 'basic_app:other' %}">Link to other.html</a>


  </body>
</html>

learning_templates/templates/basic_app/photos.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% load static %}
  {% block body_block %}
    <link rel="stylesheet" href="{% static "css/mystyle.css"%}"/>
    <h2>Circuit Connection</h2>
          <img src="{% static "images/ckt.jpg" %}" alt="Error, no pic" height="40%" width="50%">
        <h2>Simulation Screenshots</h2>
            <img src="{% static "images/Pictures_COMPLETE.jpg" %}" alt="Error, no pic" height="40%" width="50%">
    <h2>Isometric View</h2>
    <img src="{% static "images/sketch type.png" %}" alt="Error, no pic" height="40%" width="50%">
    <h2>Side View</h2>
    <img src="{% static "images/side.png" %}" alt="Error, no pic" height="40%" width="50%">
    <h2>Top View</h2>
    <img src="{% static "images/top.png" %}" alt="Error, no pic" height="40%" width="50%">
    <h1> </h1>






  {% endblock %}